// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
declare global {
    const EnterTheMatrix: typeof import("./lib/EnterTheMatrix.svelte")["default"]
    const FaCode: typeof import("./lib/FaCode.svelte")["default"]
    const FancyButton: typeof import("./lib/FancyButton.svelte")["default"]
}

export {}
